# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/AboutPage.qml) \
        $$quote($$BASEDIR/assets/DirBrowser.qml) \
        $$quote($$BASEDIR/assets/ItemPage.qml) \
        $$quote($$BASEDIR/assets/Login.qml) \
        $$quote($$BASEDIR/assets/action_icons/ic_add.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_add_entry.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_add_favorite.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_add_folder.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_add_to_contacts.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_advanced.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_advanced_restore.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_all.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_attach.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_bbm.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_browse.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_browser.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_buy.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_camera.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_cancel.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_cancel_selection.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_check_spelling.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_clear.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_clear_list.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_code_inspector.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_collapse.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_compose.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_connections.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_contacts.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_copy.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_copy_link.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_copy_link_image.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_copy_password.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_cut.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_decrease.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_delete.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_delete_prior.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_deselect.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_deselect_all.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_diagnostics.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_disable.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_doc.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_generic.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_music.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_pdf.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_picture.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_ppt.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_video.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_web.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_xls.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_doctype_zip.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_done.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_download.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_edit.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_edit_favorite.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_edit_list.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_edit_profile.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_email.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_enable.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_entry.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_expand.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_favorite.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_feedback.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_forward.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_forward_as_bbm.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_forward_as_email.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_forward_as_text.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_help.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_history.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_home.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_increase.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_info.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_location.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_lock.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_map.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_microphone.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_microphone_mute.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_move.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_nav_to.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_next.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_notes.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_notification.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_open.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_open_link.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_overflow_action.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_overflow_tab.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_paste.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_pause.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_phone.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_play.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_previous.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_properties.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_reload.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_rename.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_reply.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_reply_all.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_rotate.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_save.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_save_as.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_scan_barcode.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_search.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_select.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_select_all.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_select_more.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_select_text.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_select_text_all.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_set_as_default.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_settings.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_share.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_show_dialpad.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_show_vkb.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_sort.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_sort_filter.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_speaker.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_speaker_mute.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_stop.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_textmessage.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_to_bottom.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_to_top.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_view_details.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_view_grid.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_view_image.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_view_list.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_view_post.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_zoom_in.png) \
        $$quote($$BASEDIR/assets/action_icons/ic_zoom_out.png) \
        $$quote($$BASEDIR/assets/data.xml) \
        $$quote($$BASEDIR/assets/images/11.jpg) \
        $$quote($$BASEDIR/assets/images/documents.png) \
        $$quote($$BASEDIR/assets/images/folder.png) \
        $$quote($$BASEDIR/assets/images/upyun_logo.jpg) \
        $$quote($$BASEDIR/assets/images/upyunapp.png) \
        $$quote($$BASEDIR/assets/images/upyunapp_logo.png) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/upyun_client.cpp) \
        $$quote($$BASEDIR/src/upyun_client_impl.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/upyun_client.h) \
        $$quote($$BASEDIR/src/upyun_client_impl.h)
}

INCLUDEPATH += $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/action_icons/*.qml) \
        $$quote($$BASEDIR/../assets/action_icons/*.js) \
        $$quote($$BASEDIR/../assets/action_icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
